import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Check, UploadCloud, AudioLines, FileText, Sparkles, Copy, Play as Youtube, Camera as Instagram, BriefcaseBusiness as Linkedin, Play, Clock3, Hash, MessageSquare, Settings2, History, Wand2 } from 'lucide-react';
import { Logo } from '../components/Logo';
import { plans, examples } from '../data/marketing';

const steps = [
  { title: 'Upload your video', description: 'Add a supported video file up to 50 MB.', icon: UploadCloud },
  { title: 'Extract audio', description: 'Vireo prepares the audio for transcription.', icon: AudioLines },
  { title: 'AI transcription', description: 'Get a readable transcript with timing where available.', icon: FileText },
  { title: 'Generate content', description: 'Create platform-specific titles, hooks, captions and posts.', icon: Sparkles },
  { title: 'Review and publish', description: 'Edit, copy and publish from your own channels.', icon: Copy },
];
const features = [
  { title: 'AI transcription', description: 'Turn spoken words into a useful written starting point.', icon: AudioLines },
  { title: 'Timestamped transcript', description: 'Find key passages and revisit your source quickly.', icon: Clock3 },
  { title: 'Platform-ready drafts', description: 'Make YouTube, Instagram, LinkedIn and X copy.', icon: MessageSquare },
  { title: 'Hooks and hashtags', description: 'Find strong openings and relevant tags.', icon: Hash },
  { title: 'Creator preferences', description: 'Set your niche, audience, language and tone.', icon: Settings2 },
  { title: 'History and editing', description: 'Reopen your projects and refine generated content.', icon: History },
];
const faqs = [
  { q: 'What is Vireo?', a: 'Vireo turns an existing video into a transcript and drafts content for several social platforms.' },
  { q: 'Which video formats are supported?', a: 'The upload form accepts MP4, MOV, WEBM, AVI and MKV files. Video URL processing is planned.' },
  { q: 'What is the upload limit?', a: 'Uploaded files can be up to 50 MB.' },
  { q: 'How does transcription work?', a: 'Vireo extracts audio from your video and sends it through an AI speech-to-text service. Processing time varies by file.' },
  { q: 'Which platforms does Vireo create content for?', a: 'Vireo can draft content for YouTube, Instagram, Shorts/Reels, LinkedIn and X.' },
  { q: 'Is my uploaded video private?', a: 'Uploads are stored in a private video bucket and project access is tied to your account.' },
];
const cta = 'inline-flex items-center justify-center gap-2 rounded-xl bg-clay px-6 py-3.5 font-semibold text-white shadow-clay transition-colors hover:bg-[#c93f1e]';
export const LandingPage: React.FC = () => <div className="overflow-hidden">
  <section className="relative mx-auto grid max-w-[1350px] items-center gap-12 px-5 pb-20 pt-16 lg:grid-cols-[.9fr_1.1fr] lg:px-10 lg:pt-24">
    <div className="relative z-10"><span className="inline-flex rounded-full bg-[#fff0e9] px-4 py-2 text-xs font-semibold uppercase tracking-[.14em] text-clay">AI content repurposing for creators</span><h1 className="mt-5 max-w-[670px] font-display text-[clamp(3.2rem,5.5vw,5.7rem)] font-semibold leading-[1.05] tracking-[-.055em]">Turn one video into <span className="text-clay">scroll-stopping content.</span></h1><p className="mt-6 max-w-[580px] text-lg leading-relaxed text-muted-foreground">Upload a video and let Vireo transform it into a transcript, titles, hooks, captions, posts and platform-ready ideas.</p><div className="mt-8 flex flex-wrap gap-3"><Link className={cta} to="/signup">Generate Your First Content Kit <ArrowRight className="size-4" /></Link><a href="#how" className="inline-flex items-center gap-2 rounded-xl border border-[#e9dcd4] bg-white px-6 py-3.5 font-semibold text-forest hover:bg-cream"><Play className="size-4" /> See How It Works</a></div><p className="mt-5 text-sm text-muted-foreground">One upload. More ways to share what you made.</p></div>
    <div className="relative"><div className="absolute -inset-10 rounded-full bg-[#fff0e6] blur-[70px]" /><ProductPreview /></div>
  </section>
  <section className="border-y border-border bg-white/65 py-8"><div className="mx-auto max-w-[1350px] px-5 text-center lg:px-10"><p className="text-xs font-semibold uppercase tracking-[.2em] text-muted-foreground">Create content for every major platform</p><div className="mt-5 flex flex-wrap items-center justify-center gap-x-12 gap-y-4 font-semibold text-[#6a747a]"><span>YouTube</span><span>Instagram</span><span>Shorts / Reels</span><span>LinkedIn</span><span>X</span></div></div></section>
  <section id="product" className="mx-auto grid max-w-[1350px] gap-5 px-5 py-24 md:grid-cols-2 lg:px-10"><div className="rounded-3xl bg-[#fff4ef] p-8 md:p-12"><p className="text-xs font-bold uppercase tracking-[.2em] text-clay">The old way</p><h2 className="mt-3 max-w-md font-display text-3xl font-semibold">Repurposing video manually takes time.</h2><ul className="mt-7 space-y-4 text-[#43505a]">{['Rewatching to find useful moments','Writing every platform post from scratch','Repeating the same work after each upload'].map(x=><li key={x} className="flex gap-3"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-[#f8dbd1] text-clay">×</span>{x}</li>)}</ul></div><div className="rounded-3xl bg-[#eef5ee] p-8 md:p-12"><p className="text-xs font-bold uppercase tracking-[.2em] text-vireo-green">The Vireo way</p><h2 className="mt-3 max-w-md font-display text-3xl font-semibold text-forest">One source, a full content kit.</h2><ul className="mt-7 space-y-4 text-[#43505a]">{['Transcribe spoken content automatically','Surface useful moments and hooks','Create drafts for each platform'].map(x=><li key={x} className="flex gap-3"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-[#d7e9db] text-forest"><Check className="size-4" /></span>{x}</li>)}</ul></div></section>
  <section id="how" className="mx-auto max-w-[1350px] px-5 pb-24 text-center lg:px-10"><span className="text-xs font-bold uppercase tracking-[.2em] text-clay">How it works</span><h2 className="mt-3 font-display text-4xl font-semibold">From upload to everywhere.</h2><p className="mt-2 text-muted-foreground">Five straightforward steps from video to publishable drafts.</p><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{steps.map((s,i)=><div key={s.title} className="relative rounded-2xl border border-border bg-white p-6 text-left shadow-soft"><span className="absolute right-5 top-5 text-xs font-bold text-clay">0{i+1}</span><span className="grid size-12 place-items-center rounded-full bg-[#fff0e9] text-clay"><s.icon className="size-5" /></span><h3 className="mt-5 text-base font-semibold">{s.title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{s.description}</p></div>)}</div></section>
  <section id="features" className="bg-white/65 py-24"><div className="mx-auto max-w-[1350px] px-5 lg:px-10"><div className="text-center"><span className="text-xs font-bold uppercase tracking-[.2em] text-clay">Features</span><h2 className="mt-3 font-display text-4xl font-semibold">The essentials for modern creators.</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map(f=><div key={f.title} className="rounded-2xl border border-border bg-white p-6 shadow-soft"><span className="grid size-11 place-items-center rounded-xl bg-[#fff0e9] text-clay"><f.icon className="size-5" /></span><h3 className="mt-5 text-lg font-semibold">{f.title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{f.description}</p></div>)}</div></div></section>
  <section id="platforms" className="mx-auto max-w-[1350px] px-5 py-24 lg:px-10"><div className="text-center"><span className="text-xs font-bold uppercase tracking-[.2em] text-clay">Platform outputs</span><h2 className="mt-3 font-display text-4xl font-semibold">A better starting point for every channel.</h2><p className="mt-2 text-sm text-muted-foreground">Illustrative examples of the drafts Vireo can create.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-5">{examples.map((e,i)=><div key={e.platform} className="overflow-hidden rounded-2xl border border-border bg-white shadow-soft"><div className={`h-28 ${['bg-[#f6e1d6]','bg-[#f8e4e9]','bg-[#e9f1e9]','bg-[#e2eff5]','bg-[#e9e9e9]'][i]} p-5`}><span className="grid size-11 place-items-center rounded-xl bg-white/80 text-forest">{[<Youtube />,<Instagram />,<Play />,<Linkedin />,<span className="text-xl font-bold">𝕏</span>][i]}</span></div><div className="p-5"><h3 className="font-semibold">{e.platform}</h3><p className="mt-1 text-xs text-muted-foreground">{e.type}</p><p className="mt-4 text-sm font-medium leading-relaxed">“{e.sample}”</p></div></div>)}</div></section>
  <section id="pricing" className="bg-white/65 py-24"><div className="mx-auto max-w-[1150px] px-5"><div className="text-center"><span className="text-xs font-bold uppercase tracking-[.2em] text-clay">Plans</span><h2 className="mt-3 font-display text-4xl font-semibold">Start with the tools you need.</h2><p className="mt-2 text-sm text-muted-foreground">Paid plans are planned. Billing is not available yet.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{plans.map(p=><div key={p.name} className={`flex flex-col rounded-2xl border bg-white p-7 shadow-soft ${p.name==='Pro'?'border-clay':'border-border'}`}><div className="flex justify-between"><h3 className="font-display text-xl font-semibold">{p.name}</h3>{p.name==='Pro'&&<span className="rounded-full bg-[#fff0e9] px-2 py-1 text-xs text-clay">Planned</span>}</div><p className="mt-5 text-3xl font-semibold">{p.price}</p><p className="mt-3 min-h-[48px] text-sm text-muted-foreground">{p.description}</p><ul className="mt-6 flex-1 space-y-3">{p.features.map(f=><li key={f} className="flex gap-2 text-sm"><Check className="size-4 shrink-0 text-vireo-green" />{f}</li>)}</ul>{p.available?<Link to="/signup" className={`${cta} mt-8 text-sm`}>Get started <ArrowRight className="size-4" /></Link>:<span className="mt-8 rounded-xl border border-border px-6 py-3.5 text-center text-sm font-semibold text-muted-foreground">Coming soon</span>}</div>)}</div></div></section>
  <section id="faq" className="mx-auto grid max-w-[1150px] gap-10 px-5 py-24 lg:grid-cols-[.7fr_1.3fr]"><div><span className="text-xs font-bold uppercase tracking-[.2em] text-clay">Frequently asked questions</span><h2 className="mt-3 font-display text-4xl font-semibold">Good to know.</h2><p className="mt-4 text-muted-foreground">The practical details before your first upload.</p></div><div className="space-y-3">{faqs.map(f=><details key={f.q} className="group rounded-xl border border-border bg-white p-5"><summary className="cursor-pointer list-none pr-6 font-semibold marker:hidden">{f.q}<span className="float-right text-clay group-open:rotate-45">+</span></summary><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{f.a}</p></details>)}</div></section>
  <section className="mx-auto max-w-[1350px] px-5 pb-20 lg:px-10"><div className="relative overflow-hidden rounded-[28px] bg-forest px-8 py-14 text-white md:px-16"><div className="absolute -right-14 -top-24 size-80 rounded-full border-[50px] border-white/5" /><div className="relative"><Wand2 className="size-7 text-[#aed19b]" /><h2 className="mt-4 max-w-xl font-display text-4xl font-semibold">Turn one video into your next week of content.</h2><p className="mt-3 max-w-lg text-[#d1e0d7]">Bring the video. Vireo helps you shape everything that comes after.</p><Link to="/signup" className={`${cta} mt-7`}>Start Creating <ArrowRight className="size-4" /></Link></div></div></section>
</div>;

function ProductPreview(){ return <div className="relative rounded-[22px] border border-border bg-white p-3 shadow-lift"><div className="flex gap-3"><div className="hidden w-28 shrink-0 rounded-xl bg-[#f8faf7] p-3 sm:block"><Logo compact /><div className="mt-7 space-y-3 text-[10px] text-[#56615e]"><p className="rounded-md bg-[#e5f1e8] p-2 font-semibold text-forest">◉ Dashboard</p><p className="p-2">⊕ New Project</p><p className="p-2">◷ History</p><p className="p-2">⚙ Settings</p></div></div><div className="min-w-0 flex-1"><div className="flex h-8 items-center rounded-lg bg-[#f7f7f5] px-3 text-[10px] text-muted-foreground">Search projects and content…</div><div className="mt-3 rounded-xl bg-[#eef4ef] p-5"><p className="text-[10px] font-semibold uppercase tracking-widest text-vireo-green">Your content kit</p><h3 className="mt-2 text-xl font-semibold text-forest">One video. Five fresh ways to share it.</h3><p className="mt-2 text-xs text-muted-foreground">Transcripts, hooks, captions and posts in one workspace.</p><div className="mt-5 flex flex-wrap gap-2">{['YouTube','Instagram','Shorts','LinkedIn','X'].map(x=><span key={x} className="rounded-lg bg-white px-2.5 py-2 text-[10px] font-semibold text-forest shadow-soft">{x}</span>)}</div></div><div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded-xl border border-border p-4"><div className="flex items-center gap-2 text-xs font-semibold"><FileText className="size-4 text-vireo-green" />Transcript</div><div className="mt-3 space-y-2"><span className="block h-2 w-full rounded bg-[#e6eee8]"/><span className="block h-2 w-4/5 rounded bg-[#e6eee8]"/><span className="block h-2 w-3/5 rounded bg-[#e6eee8]"/></div></div><div className="rounded-xl border border-border p-4"><div className="flex items-center gap-2 text-xs font-semibold"><Sparkles className="size-4 text-clay" />Content drafts</div><p className="mt-3 text-[11px] text-muted-foreground">A clear title and an opening that makes people stop scrolling.</p></div></div></div></div><span className="absolute -bottom-4 right-6 rounded-full bg-white px-4 py-2 text-[10px] font-semibold text-forest shadow-lift">Illustrative product preview</span></div> }
